### ISSUE TITLE
RS0002.1.2 Crear lanzador de app desde NetBeans

### ISSUE THREAD

**Issue by molguin92** [jSwingRipples/jswingripples#4]
- Descripción: Desarrollar plug-in que permita abrir la aplicación desde Eclipse.
- Fuente: Analista.
- Prioridad: Crítico.
- Estabilidad: Intransable.
- Fecha Actualización: 06/06/2016
- Estado: Cumple
- Incremento:
- Tipo: Funcional.
- Ususario Asociado: End-User.

Requisitos de Usuario Asociados:
- [RU0002 - Desarrollar plugins de integración liviana con IDEs](https://github.com/jSwingRipples/jswingripples/wiki/RU0002)

**Comment by noahmelto** [comment]
## Initialization

Lanzar desde NetBeans jSwingRipples

## Concept Location

Plug-in, NetBeans, parameter, file.

## Impact Analysis

Ninguna clase de JSwingRipples se verá afectada.

## Prefactoring

## Actualization

Limpieza de código sistemática

## PostFactoring

## Conclusion

**Comment by noahmelto** [comment]
Closed with https://github.com/jSwingRipples/netBeansPlugin/pull/1
