### ISSUE TITLE
RS0002.2.2 Incluir parámetros para la ubicación de la carpeta del proyecto desde NetBeans

### ISSUE THREAD

**Issue by molguin92** [jSwingRipples/jswingripples#6]
- Descripción: Incluir en el plugin de NetBeans los parámetros para la ubicación de la carpeta del proyecto desde NetBeans. Esto permitiría abrir archivos para editar individualmente o en modo "batch".
- Fuente: Analista.
- Prioridad: Crítico.
- Estabilidad: Intransable.
- Fecha Actualización: 06/06/2016
- Estado: No_Cumple
- Incremento:
- Tipo: Funcional.
- Ususario Asociado: End-User.

Requisitos de Usuario Asociados:
- [RU0002 - Desarrollar plugins de integración liviana con IDEs](https://github.com/jSwingRipples/jswingripples/wiki/RU0002)

**Comment by noahmelto** [comment]
## Initialization

Integrar en el plug-in de NetBeans la posibilidad de dar como parámetro la posición de un único o un grupo de archivos a analizar.

## Concept Location

Plug-in, NetBeans, parameter, file.

## Impact Analysis

Se verá afectada la clase ...

## Prefactoring

## Actualization

## PostFactoring

## Conclusion
